- name: configure catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs and mongodb
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop: 
    - nodejs
    - mongodb-mongosh

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app
      comment: "Roboshop system user"

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete catalogue zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: Download catalogue file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: urarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: installing dependencies
    community.general.npm:
      path: /app

  - name: copying catalogue service file
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes