- name: configure shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "Roboshop user"

  - name: removing app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: removing default zip
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: downloading the code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzipping the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: install dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copying shipping service
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  # - name: install dependencie
  #   ansible.builtin.pip:
  #     name: "{{ item }}"
  #     executable: pip3.9
  #   loop:
  #   - cryptography
  #   - PyMySQL

  - name: import shipping data
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
